### ISSUE TITLE
Update docs with updated images of the new UI

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerseDocs#295]
### Describe the bug
In pages like [this](https://docs.circuitverse.org/#/groups) we have screenshots of the old UI.

### To Reproduce
1. Go to [link](https://docs.circuitverse.org/#/groups)
2. Scroll to see screenshots of older UI

### Expected behavior
Replace old screenshots / images with images for the new UI

### Are you working on this issue? (Yes/No)
No

**Comment by Shivansh2407** [comment]
Hey @sal2701, Thanks for pointing it out. This is updated in #282 by Pragati During GSoD 2020, and we'll be merging it soon after updating some things in the PR. Please checkout this PR and let me Know if you find out some issues in this, and raise issues here so that they can be fixed as well.
Keep Contributing 🎉
